"""empty message

Revision ID: de4ad82551fe
Revises: 
Create Date: 2023-04-03 17:25:41.061217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4ad82551fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantcompare',
    sa.Column('compare_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('left_Species_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('right_Species_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tip', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('compare_id')
    )
    op.create_index(op.f('ix_plantcompare_compare_id'), 'plantcompare', ['compare_id'], unique=False)
    op.create_table('userlist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_nickname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_password', sa.VARCHAR(), nullable=False),
    sa.Column('Is_superuser', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('Access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'user_nickname'),
    sa.UniqueConstraint('user_nickname')
    )
    op.create_index(op.f('ix_userlist_user_id'), 'userlist', ['user_id'], unique=False)
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('Compare_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Compare_id'], ['plantcompare.compare_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comment_comment_id'), 'comment', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_userlist_user_id'), table_name='userlist')
    op.drop_table('userlist')
    op.drop_index(op.f('ix_plantcompare_compare_id'), table_name='plantcompare')
    op.drop_table('plantcompare')
    # ### end Alembic commands ###
